version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT:-3000}:3000
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-articles_db}
      POSTGRES_HOST: db
      CORS_ORIGIN: ${BASE_URL}
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_BACKEND_BASE_URL: ${BASE_URL}
        VITE_BACKEND_PORT: ${BACKEND_PORT:-3000}
    ports:
      - ${FRONTEND_PORT:-80}:80
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-articles_db}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: